name: Release CNB

on:
  release:
    types:
      - created
# on: [push] # Could use to push tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.40.0
        with:
          ruby-version: 2.6.6
      - uses: actions/checkout@v2
      - name: bundle install
        run: bundle install --jobs 4 --retry 3
      - name: build tar file
        run: bundle exec rake buildpack:tarball
      - uses: actions/upload-artifact@v2
        with:
          name: buildpack.tgz
          path: buildpacks/*

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Get Version'
        run: |
          [[ $GITHUB_REF =~ ^refs\/tags\/(.*)$ ]] && version=${BASH_REMATCH[1]}
          echo "::set-env name=VERSION::$version"
      - name: 'Download list binary'
        uses: actions/download-artifact@v2
        with:
          name: buildpack.tgz
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.upload_url }}
          asset_path: ./buildpack.tgz
          asset_name: heroku-buildpack-ruby-${{ env.VERSION }}.tgz
          asset_content_type: application/gzip
